# Generated by Django 4.2.4 on 2023-08-12 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.IntegerField(unique=True, verbose_name='Kakao_id')),
                ('nickname', models.CharField(max_length=128, verbose_name='Sense NickName')),
                ('post_count', models.IntegerField(verbose_name='Post Count')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('content', models.CharField(max_length=128, verbose_name='content')),
                ('report_count', models.IntegerField(verbose_name='Report Count')),
                ('kakao_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kakaouser')),
            ],
        ),
    ]
